### ISSUE TITLE
not possible to connect to GUI Synology 218+

### ISSUE THREAD

**Issue by RoboPete** [oznu/homebridge-syno-spk#64]
After the update from version 2.0.0 to 2.2.1 the GUI can no longer be called up. I uninstalled 2.2.1 and installed 2.0.0 again, but that didn't help.
Please advise.

**Comment by RoboPete** [comment]
hb-service.js execute permissions not allowed....this is the Problem👍

**Comment by meru-zz** [comment]
i have the same Problem.

Can open the GUI "Failed to open the page"

**Comment by cristian5th** [comment]
I'm having the same problem with a DS418.

I have DSM 7.0.1-42218 and I installed the armv8 package of the homebridge-syno.

When I launch the Homebridge GUI, I get the failed to open page error because it can't connect to the server. I have other applications in the same server with different ports and they are all reachable except the Homebridge.

Any idea about what configuration can I touch to make it work?
