### ISSUE TITLE
"Package not supported"

### ISSUE THREAD

**Issue by drp-daniel** [oznu/homebridge-syno-spk#74]
Hi, 

I'm trying to install homebridge-braswell-2.2.1.spk (also tried 2.2.0 and 2.0.0) on my Synology NAS with DSM 7.0.1.
It's the first time trying to install Homebridge to my Synology because I want to use my Raspberry Pi for something else.
Everytime I try, I get this error message.
![image](https://user-images.githubusercontent.com/99918961/154569677-b62a3037-85f9-4674-9e58-dc32055fa0e8.png)

Do you have any ideas how to fix it?

My Synology: 
DS415play
INTEL Atom CE5335
DSM 7.0.1-42218 Update 2

**Comment by drp-daniel** [comment]
I tried V 2.2.2 now. But I received the same error.

**Comment by Obikela88** [comment]
Got the same issue. Tried v2.2.1. 

Got a DS416 with
DSM 7.0.1-42218 Update 3
ANNAPURNALABS Alpine AL212

**Comment by yakobe** [comment]
I am also trying to get this running on a DS214play (INTEL Atom CE5335) with DSM7. @oznu is there any way to tweak this to get it working or has my NAS started to reach the end of it's compatibility life 😄

**Comment by oznu** [comment]
It requires an arm64 CPU - the models listed above are not arm64. Typically this seems to be the 2018 or later models.

**Comment by oznu** [comment]
More models are now supported:

https://github.com/oznu/homebridge-syno-spk/releases/tag/2.2.4

x86_64 - All Intel / AMD 64 bit CPU Models
armv8 -  DS120j, DS119j
armada38x (armv7) - DS419slim, DS218j, RS217, RS816, DS416j, DS416slim, DS216, DS216j, DS116
armv7 - DS1817, DS1517, DS416, DS2015xs, DS1515, DS715, DS215+

@yakobe  @drp-daniel  - the DS214play / DS215play have 32 bit CPUs, rather than 64 bit, these will never be supported as Node.js does not do official builds for 32 bit linux.

**Comment by oznu** [comment]
DS214play / DS215play should be supported as of 3.0.6.
