### ISSUE TITLE
Error loading shared library - libatomic.so

### ISSUE THREAD

**Issue by gerarddvb** [oznu/homebridge-syno-spk#85]
Thank you!!!!!
I am finally running Homebridge on my DS218j (armada38x) with the 3.0.1 version.

My Nest, Samsung TV and weathersation plugins work.
But my Ring plugin installs, but after install i cannot configure in the config UI.
If I reset Homebridge, i get this in logs;

[Homebridge UI] [homebridge-ring] /volume1/@appstore/homebridge/app/bin/node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
[Homebridge UI] [homebridge-ring] Child process ended
[Homebridge UI] [homebridge-ring] Terminating child process...

Do you think this is a problem with the Ring plugin or with syno-spk?

**Comment by oznu** [comment]
Spk / ui issue. I'll look at it soon.

**Comment by oznu** [comment]
Hi @gerarddvb,

Could you try this one and manually install it? (You can install it over the top of your existing one):

https://github.com/oznu/homebridge-syno-spk/releases/download/3.0.2-test.1/homebridge-armada38x-3.0.2_debug.spk

**Comment by gerarddvb** [comment]
Hi, I tried to update but after that the 8581 UI does not open anymore. 
If I remove the package, delete the homebridge folder and do a clean install I get same result.
The homebridge folder stays empty on an fresh 3.0.2 install.

If I remove 3.0.2 and do a fresh 3.0.1 install it starts working again.

**Comment by oznu** [comment]
Sorry, that .spk had the wrong arch of node.

My fix didn't work anyway, I can only installed shared libraries like libatomic.so in `/usr/local/lib`, but Node.js by default does not look in `/usr/local/lib`, only `/usr/lib`. As the Synology package installer is pretty locked down, I can't put anything in `/usr/lib`.

To get around this I had set the `LD_LIBRARY_PATH` environment variable to tell node to look for the library in `/var/packages/homebridge/target/app/lib` -  however due to the way the UI was spawning the child process for the Ring settings page, all previously set env vars were being stripped.

I've done two things to remediate this:

* I've patched the UI in `v4.43.3-test.13` to preserve the environment when spawning a child process for plugin config scripts.
* Anticipating there may be other cases where the `LD_LIBRARY_PATH` environment variable is not passed, I've added a simple command that can be run by the user as root via SSH that will install `libatomic.so` in `/usr/lib`:

```
sudo hb-service install-libatomic-lib
```

and it's counterpart to remove it:

```
sudo hb-service remove-libatomic-lib
```

**Comment by gerarddvb** [comment]
Thank you very much!!

It works, only the videostream from Ring has no sound. 
I don't really care, I only use it in homebridge for HomePod/AppleTV doorbell functions.

Installing the patched UI v4.43.3-test.13 via SSH did not seem to work.
Managed to install it via Terminal in config UI.
I used this command: `pnpm install --save homebridge-config-ui-x@test`

After that it started working.

__________

I cannot install install-libatomic-lib via the hb-service command (Not sure if it is still needed).
This is the output it get:

G@Server:~$ sudo hb-service install-libatomic-lib
Usage: hb-service [restart|logs|status|update-node]

This hb-service command is provided by Homebridge Synology Package

Please provide a command:
    restart                          restart the homebridge service
    add <plugin>@<version>           install a plugin
    remove <plugin>@<version>        remove a plugin
    update-node [version]            update Node.js
    logs                             tails the homebridge service logs
    status                           check if the Homebridge UI web server is running
    shell                            open the Homebridge Terminal

See the wiki for help with hb-service: https://homebridge.io/w/JTtHK

__________

This is the output I get in homebridge from Ring.
Seems like libfdk_aac is missing.

5/6/2022, 4:13:31 PM] [Ring] Preparing Live Stream for Voordeur
[5/6/2022, 4:13:31 PM] [Ring] Streaming video only - found ffmpeg, but libfdk_aac is not installed. See https://github.com/dgreif/ring/wiki/FFmpeg for details.
[5/6/2022, 4:13:32 PM] [Ring] Waiting for stream data from Voordeur (0.942s)
[5/6/2022, 4:13:32 PM] [Ring] Received stream data from Voordeur (1.228s)
[5/6/2022, 4:13:32 PM] [Ring] Streaming active for Voordeur
[5/6/2022, 4:13:52 PM] [Ring] Stopped Live Stream for Voordeur

**Comment by oznu** [comment]
> I could not install install-libatomic-lib via the hb-service command you provided (Not sure if it is still needed).

I haven't published that change yet. Great to hear you've got it working.

**Comment by oznu** [comment]
Solution documented in wiki: https://github.com/oznu/homebridge-syno-spk/wiki/DSM-7:-Error-loading-shared-library---libatomic.so
