### ISSUE TITLE
No Response after update 7.1-42661 Update 3 

### ISSUE THREAD

**Issue by icoltro** [oznu/homebridge-syno-spk#92]
After the update, all devices show me status "No Response"

**Comment by oznu** [comment]
I updated my two of my arm-based test units (DS216j and DS120j) from `DSM 7.1-42661 Update 1` to `DSM 7.1-42661 Update 3` and could not replicate this issue. The package remained installed, restarted correctly, and the connection to HomeKit persisted.

**Comment by SimonLawson70** [comment]
Seeing the same problem - since I installed 7.1-42661 update 3, every bridged accessory is now showing "No Response". Homebridge package 3.0.8 on a DS916+ (Intel Pentium N3710 with 8GB). I've completely removed and reinstalled the Homebridge package and all the plugins one by one, nothing seems to help.

**Comment by luk4s** [comment]
Yesterday I updated Homebridge in DSM and same result. Homebridge works, but in Home.app all accessories "no response". 
Re-add bridge show something like "error try reset bridge"...
